<a href="https://colab.research.google.com/github/gcalvin817/R/blob/master/Math404_Stats_Book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **1.1 Mathematical Operators in Python**

Python offers numerous data types to represent numbers and logic values. These are given below:

In [1]:
x = True
type(x)  # it returns the type of x as bool.

bool

* **Integer:** An integer is a whole number without any fractional part. For instance, 5 is a whole number; it is an integer. Conversely, 5.0 is not an integer because it has a decimal part. Integers are represented by the data type **int** in Python.


* **Float:** A floating-point number contains a decimal part. For example, 3.5 is a floating-point number. Python stores floating- point values in the data type **float.**

* **Complex:** A complex number comprises of paired numbers: a real number and an imaginary number. The imaginary part of a complex number always appears with a j.

  1. cmplx_no = 2 + 8j
  
  
* **Bool:** Logical arguments require Boolean values represented by data type Bool in Python. A variable of type **Bool** can either be **True** or **False.** The first letter of both keywords is capital. We can assign a Boolean value to any variable using the keywords True or False as

Alternatively, to define a Bool variable, we create an expression
that defines a logical idea. As an example,

In [2]:
bool_variable = 8 < 4
bool_variable

False

returns False because 8 is not smaller than 4.

### **1.1.1 Arithmetic Operators**

To perform addition, subtraction, multiplication, and division, we use arithmetic operators +, -, *, and /, respectively. Arithmetic operations can be combined using parentheses ( ). To understand the working of these operators, type the following code.

In [3]:
3 + 10 - 6

7

In [4]:
30 - 5 * 8

-10

In [5]:
20 / 8 # division returns a floating-point number

2.5

To get an integer result from division by discarding the fractional part, we use the // operator.

In [6]:
20 // 6

3

To calculate the remainder, we use the % operator.

In [7]:
20 % 6

2

To calculate powers in Python, we use the ** operator.

In [8]:
4 ** 2

16

Operations involving int and float type operands return the output having the data type float.

In [9]:
type(6 * 5.3)

float

Python supports complex numbers. It uses the suffix j or J to indicate the imaginary part of a complex number. To create a complex number, we type the following command.

In [10]:
3 + 2j

(3+2j)

### **1.1.2 Assignment Operators**

* A $\textit{variable}$ is used to store the operands and results of the operations performed on these operands. It can be considered as a container that holds our information.


* We store our results in a Python Notebook using variables. We make an assignment to a variable to store our data. Various assignment operators supported by Python are given below. The equal sign (=) is used to assign a value to a variable.

In [11]:
exam1 = 89
exam2 = 78
sum1 = exam1 + exam2

* Variable names in Python are case-sensitive. It means that variable name height and Height are not the same.


* If a variable is not assigned any value (not defined), we get an error when we try to use it:

In [12]:
sum1

167

* The following code assigns value 10 to my_var, then adds value 20 to it. Thus, the result stored in my_var becomes 30.

In [13]:
my_var = 10
my_var -= 20
my_var

-10

### **1.1.3 Logical Operators**

* Logical operators work on logical operands that can assume one of two values: `True` and `False`. The logical operators used in Python are given below.

**$\textbf{Logical and:}$** It returns `True` only when both the operands are true

In [14]:
x = True
y = False
x and y

False

$\textbf{Logical or:}$ It returns True if either of the operands is true.

In [15]:
x = True
y = False
x or y

True

$\textbf{Logical not:}$ It complements the operand.

In [16]:
x = True
not x

False

### **1.1.4 Comparison Operators**

* Comparison operators are used to find the relationship between two operands if they are equal, or one of the operands is greater than another operand, or vice versa.


* These operators return either True or False, and they are extensively employed to make decisions in programming. The details of comparison operators are given below.


Let x = 6 and y = −8 be the operands.

$\textbf{Equal (==):}\,\, $  It checks if both operands x and y are equal.

In [17]:
x == y

False

$\textbf{Not equal (!=):}\,\, $ It checks if both operands x and y are not equal.

In [18]:
x != y

True

$\textbf{Greater than (>):}\,\, $ It checks if one operand is greater than the other operand.

In [19]:
x > y

True

$\textbf{Less than (<):}\,\, $ It checks if one operand is smaller than the other operand.

x < y

$\textbf{Greater than or eqaul to (>=):}\,\,$ It checks if one operand is greater than or equal to the other operand.

In [20]:
x >= y

True

$\textbf{Less than or eqaul to (<=):}\,\,$ It checks whether one operand is less than or equal to the other operand.

In [21]:
x <= y

False

### **1.1.5 Membership Operators**

* These operators are used to find whether a particular item or set of items are present in a collection or not. The membership operators are **in** and **not in**.


* They are used to test whether a value or variable is found in a sequence such as string, list, tuple, set, and dictionary.


These operators are used in the following example.

In [22]:
x = 'Hello world' ## x is a string of characters
print('h' in x) ## returns True if ‘H’ is in x
print('Hello' not in x) ## returns True if ‘Hello’ is not present in x

False
False


## **1.2 String Operations**

* Text data includes numbers, alphabets, spaces, and special characters such as comma, full stop, and colon.


* Python represents text using a string data type. It provides us with rich resources to manipulate strings.


* Since computers work on binary numbers, they convert string characters into numbers using a standard called *Unicode*.


* This number is then stored in memory. For instance, the letter A is converted to its Unicode 65. Type ord(“A”) in the Jupyter cell and press Enter to observe 65 as an output.

In [23]:
ord("Z")

90

In Python, strings are specified either by:

* Enclosing characters in single quotes (‘...’) or


* Enclosing characters in double quotes (“...”)


In Python, a string is an array of bytes representing Unicode characters. A single character is a string with a length of 1. Type the following code to observe the output.

In [24]:
a = 'An example string in single quotes.'
print(a)
print('example' not in a)

An example string in single quotes.
False


In [25]:
'A string in double quotes.'

'A string in double quotes.'

Multiple strings can be specified and printed using the print statement. A comma is used to separate different strings. Try the following code to print multiple strings. The print( ) function omits the enclosing quotes in the output.

In [26]:
print('margo', 'and apple', 'are fruits')

margo and apple are fruits


We get an error message when we try to print a single quote in a string enclosed in ‘…’. The same error message is displayed if we try to print a double quote in a string enclosed in “…”.

In [30]:
print('Why don't we visit the museum?')

SyntaxError: unterminated string literal (detected at line 1) (<ipython-input-30-720eced34847>, line 1)

To print such characters, we use backslash \ , called the escape character.

In [31]:
print('Why don\'t we visit the museum?')

Why don't we visit the museum?


Special tasks can be performed using escape characters. For example, \t generates a tab.

In [32]:
print('Why don\'t we visit \t the museum?')

Why don't we visit 	 the museum?


While \n produces a new line within the print statement.

In [33]:
print('Why don\'t we visit \n the museum?')

Why don't we visit 
 the museum?


Suppose we want to display the path of a directory such as C:\new_directory using a print statement.


* We will get a new line because \n in the directory name produces a new line.


* To ignore the new line, we use the letter r at the start of the directory name as follows:

In [34]:
print(r'c:\new_directory')

c:\new_directory


The operator + can be used to concatenate strings together.

In [35]:
mystr1 = 'Statistics'
mystr2 = 'using'
mystr3 = 'Python'
mystr1 + mystr2 + mystr3

'StatisticsusingPython'

### **String Indexing**

The string elements, individual characters, or a substring can be accessed in Python using positive as well as negative indices. Indexing used by Python is shown below:

In [36]:
from IPython import display
display.Image("/Users/calvingayeii/Library/CloudStorage/OneDrive-Personal/Lecture2024/LinearAlgebraPYTHON/googleColabs/p.png")

FileNotFoundError: No such file or directory: '/Users/calvingayeii/Library/CloudStorage/OneDrive-Personal/Lecture2024/LinearAlgebraPYTHON/googleColabs/p.png'

FileNotFoundError: No such file or directory: '/Users/calvingayeii/Library/CloudStorage/OneDrive-Personal/Lecture2024/LinearAlgebraPYTHON/googleColabs/p.png'

<IPython.core.display.Image object>

Square brackets are used to access string elements. For
instance:

In [37]:
x = "This is a test string"
print(x[0])

T


In [38]:
print(x[-1])

g


A substring can be extracted from a string using indexing. This process is known as **string slicing**. If x is a string, an expression of the form x[i1:i2] returns the x from position i1 to just before i2. A range of indices is specified to access multiple characters of a string.

In [39]:
print(x[0:9])

This is a


The characters of x from index 0 to 8 are returned by the aforementioned statement. The index 9 is not included. To get string characters from a specific index to the last index, we
may type the following statement.

In [40]:
print(x[8:len(x)])

a test string


If we want to get every kth character in the string, we specify a **stride** or a **step** in the string indexing. A stride or a step specifies the size of the step between string characters. A
stride is set if we add an additional colon in string indexing. For example, to retrieve every second character of the string x starting from index 1 to index 11, we specify a step of 2 as
follows:

In [41]:
x = "This is a test string"
x[1:12:2]

'hsi  e'

In [42]:
x = "This is a test string"
x[:0:-2]

'git stas i'

Note that the first character of string x, T, is not displayed because we have specified a range of indices from end to 1 (index 0 is not included). We get a different output when we write the following script.

In [43]:
x = "This is a test string"
x[::-2]

'git stas iT'

To replicate a string multiple times, we use the operator *. To generate five copies of the string ‘Hello,’ type:

In [44]:
str = 'Hello ' * 5
print(str)

Hello Hello Hello Hello Hello 


In Python, strings can be manipulated using numerous builtin methods (functions). The method **strip( )** eradicates any whitespace from the beginning or the end of a string.

In [45]:
str1 = "        This is a test string"
print(str1.strip())

This is a test string


To convert a string to lower case, we use the method **lower( )**.

In [46]:
str2 = "This is a text string"
print(str2.lower())

this is a text string


To convert a string to upper case, we use the method **upper( )**.

In [47]:
str3 = "This is a text string"
print(str3.upper())

THIS IS A TEXT STRING


To replace the characters of a string, we use the method **replace( )**.

In [48]:
str4 = "I ate a banana"
print(str4.replace("banana", "mango"))

I ate a mango


To break a string into smaller strings, we use the method **split( )** along with a specified separator.

In [49]:
str5 = 'Hi mate, how do you do?'
print(str5.split(","))

['Hi mate', ' how do you do?']


In the aforementioned code, we have used a comma as a separator. Other characters can also be specified to serve as separators.

## **1.3 Conditional Statements and Iterations**

Conditional statements are used when we need to make decisions in our program. A block of code is executed only if a certain condition is satisfied, and a different piece of code is run otherwise. Conditional statements provided by Python are:

 1. if,
 2. elif, and
 3. else


 **`If`** statements can be used standalone, but **`elif`** and **`else`** statements are always accompanied by a corresponding if statement. We give the details and usage of these statements in the following sections.

### **1.3.1 If, Elif, and Else Statements**

### **if(condition)**

In [50]:
student_marks = 90
if(student_marks > 70):
    print("Marks could be 90.")


Marks could be 90.


In [51]:
print('Enter marks obtained by a student:')
student_marks = int(input())
if(student_marks > 100):
    print("Marks exceed 100.")

Enter marks obtained by a student:
56


### **else Statement**

The statement **else** is always accompanied by an accompanying if statement, i.e., **if-else.** The syntax of if-else is given below


`if(condition):`


Indented statement(s) when the condition is True


`else:`


Indented statement(s) when the condition is False
In our previous examples on student marks, let us display the message “Outstanding” if student_marks are 80 or greater. A message “Not outstanding” is displayed otherwise.

In [52]:
print('Input marks of a student')
student_marks = int(input())
if(student_marks >= 80):
    print("Outstanding")
else:
    print("Not outstanding")

Input marks of a student
67
Not outstanding


### **Nested Decisions**

To make decisions under multiple conditions, Python allows us to perform nested decisions. The **`if-elif-else`** statements are employed to accomplish nested decisions. Continuing
with the example of student marks, if the marks of a student are greater than 100 or less than 0, a warning should be displayed. Additionally, if the obtained marks are 80 or greater, Outstanding should be displayed. Otherwise, Not outstanding should be displayed.

In [53]:
print('Enter marks of a student')
student_marks = int(input())
if(student_marks > 100 or student_marks < 0):
    print("Invalid marks.")
elif(student_marks >= 80):
    print("Outstanding")
else:
    print("Not outstanding")

Enter marks of a student
87
Outstanding


Note that we have used a logical operator **`or`** to combine two conditions together inside the if statement.

[Further Reading on conditional statements](https://www.techbeamers.com/python-if-else/)

### **1.3.2 For Loop**

* Iteration statements provided to us by Python allow us to perform a task more than once.


* A for loop is used to iterate a task a fixed number of times. For loop has a definite beginning and end.


* We provide a sequence or a variable to the loop as an input that causes the loop to execute a fixed number of times. T


* the syntax of a for loop is given as.


`for loop_variable in sequence:`

In [54]:
subjects = ['Probability', 'Statistics', 'Machine Learning',
            'Data Science', 'Artificial Intelligence']

for k in subjects:
  print(k)

Probability
Statistics
Machine Learning
Data Science
Artificial Intelligence


In this example, "subjects"  is a variable containing five items.
This is used to decide the number of iterations of a for loop.
The loop runs five times because the number of items in the
variable subjects is five.

* The function `range()` is normally used in a for loop to generate
a sequence of numbers.

* For example, `range(5)` generates numbers from 0 to 4 (five numbers). The following code generates the first five numbers.

In [55]:
for k in range(5):
  print(k)

0
1
2
3
4


* We can also specify a step size other than 1 within the `range() function` as follows:

In [56]:
for x in range(3, 39, 3):
    print(x)

3
6
9
12
15
18
21
24
27
30
33
36


* In `range(3, 12, 3)`, 3 is the step size. The statements **break** and **continue** are sometimes used inside the loops.

* The **break statement** discontinues the execution of the loop.

* The **continue statement** skips all the statements of the for loop following the continue statement.

* The usage of both statements is illustrated in the following example.

In [57]:
students = ['Adam', 'Alice', 'Bob', 'Emma', 'Julia']

for k in students:
    if k == 'Bob':
        continue
    print(k)
    if k == 'Emma':
        break

Adam
Alice
Emma


* The name Bob is not printed in the output because the continue statement is executed when the value of k equals Bob.

Note that `print(k)` statement is not indented with the if statement. Thus, it is not part of the if statement. Moreover, the code breaks right after it has printed the name, Emma.

### **1.3.3 While Loop**

* The **`while`** loop iteratively runs certain statements until its condition is fulfilled. The syntax of the while loop is given below.


* while (condition):
    
       Statement(s) to be executed in the while loop
       
       
* For instance, to add natural numbers up to the number input by a user, we use a while loop as follows:

In [58]:
# This program finds the sum of the first
# n natural numbers, where the value of n is
# input by the user

n = int(input("Input an integer = "))

# initialixe variables sum and j (counter)

sum = 0
j = 1
while j <= n:
    sum = sum + j
    j = j+1   # update the counter variable
print("First", n, "natural numbers add up to",
      sum)

Input an integer = 87
First 87 natural numbers add up to 3828


* The user of this program is asked to input a natural number upon execution of this program.

* A sum of 10 is obtained if the number 4 is entered, and a sum of 55 is returned upon entering the number 10.

* The **`while loop`** allows us to use the `break`, `continue`, and `else` statements inside a while loop like a **`for` loop.**

#### **Nested Loop**

A `loop`, either **`for`** or **`while`** can be used inside another loop. This is known as **nested loops** that can be used when we work with the data in two-dimensions.

* The following program uses two for loops, one nested inside another, to print all the combinations of two variables.

In [59]:
attributes = ["heavy", "wooden", "fast"]
objects = ["chair", "table", "computer"]
for j in attributes:
    for k in objects:
        print(j, k)

heavy chair
heavy table
heavy computer
wooden chair
wooden table
wooden computer
fast chair
fast table
fast computer


## **1.4 Functions in Python**

* A function is defined as a piece of code that is used to perform a specific task.


* Functions execute when they are called by their names.


* Python permits us to define/create functions using the keyword **`def`**.


* For instance, to define a function named my_function1, we write the following code:

In [60]:
def my_function1():
    print("This is a test function")

To run this function, we type its name.

In [61]:
my_function1()

This is a test function


A **`function`** can accept one or more inputs by passing parameters or arguments inside the parentheses ( ).

* For instance, the following function accepts a  string as its input.

In [62]:
def my_function2(str_in):
    print("This function prints input that is " +
          str_in)

my_function2("computer")
my_function2("table")
my_function2("chair")

This function prints input that is computer
This function prints input that is table
This function prints input that is chair


* If a **`*`** is added before the parameter name while defining the function, an input of variable size can be passed as input / argument to the function. Thus, the function is able to receive multiple inputs.


* The following function elaborates on this idea.

In [63]:
def my_function3(*myfruits):
    print(myfruits[1], "is my favorite fruit.")
my_function3("Mango", "Apple", "Orange")  # 3 inputs.

Apple is my favorite fruit.


In [64]:
my_function3("Mango", "Orange", "Apple", "Apricot")
# 4 inputs

Orange is my favorite fruit.


* Data can be returned from a function when we use the **`return`** statement as follows.

In [65]:
def mult_by_10(k):
    return 10 * k
print(mult_by_10(2))
print(mult_by_10(-9))
print(mult_by_10(100))

20
-90
1000


* Python allows us to define a function without any name.

* This is called a **lambda function** (anonymous function), which can receive multiple input arguments but has only one statement.


* To define a lambda function, we use

         lambda arguments : statement
         
* To illustrate the creation and use of a lambda function, we may type the following code:


* The below lambda function subtracts 10 from each input number

In [66]:
x = lambda input_number: input_number - 10
print(x(10))
print(x(-10))
print(x(20))

0
-20
10


## **1.5 Data Structures**

In addition to commonly used data types **`int`**, **`float`**, and **`str`**, Python offers data types to store a collection of multiple entries from numbers, alphabets, alphanumeric, strings, and special characters.

The four commonly used collection data types provided by Python are as follows.


* **`List`** is a mutable and ordered collection that allows duplicate entries.


* **`Tuple`** is an immutable and ordered collection that also allows duplicate entries.


* **`Set`** is an unordered and unindexed collection that, like real sets, prohibits duplicate entries.


* **`Dictionary`** is a mutable, unordered, and indexed collection of entries that prohibits duplicate entries.


The following sections discuss these data types and their usages

### **1.5.1 Lists**

* A **`list`** is a mutable and ordered collection of elements.


* **`Lists`** are specified using square brackets in Python. For instance, to create a list named item_list, type the following code:

In [67]:
item_list = ["backpack", "laptop", "ballpoint",
            "sunglasses"]
print(item_list)

['backpack', 'laptop', 'ballpoint', 'sunglasses']


* To access any particular element/item of a list, we refer its index number.

* For instance, to print the third item of the list, we type the following code:

In [68]:
print(item_list[2])

ballpoint


In [69]:
print(item_list[0])

backpack


Since Python permits negative indexing, we can use them to
access elements of a list.


* As an example, the following piece
of code prints the third last item of the list.

In [70]:
item_list = ["backpack", "laptop", "ballpoint",
             "sunglasses"]
print(item_list[-3])

laptop


To return the second and the third list items, we type the following code.

In [71]:
print(item_list[1:3]) # Elements at index 1 and 2
                         #but not the one at 3

['laptop', 'ballpoint']


Try the following, and observe the output:

In [72]:
print(item_list[:3])


print(item_list[2:])


print(item_list[-3:-1])

['backpack', 'laptop', 'ballpoint']
['ballpoint', 'sunglasses']
['laptop', 'ballpoint']


* The index of a specific element can be used to change the value of that element.


* For instance, to change the second element of the `item_list`, type the following:

In [73]:
item_list[1] = "computer"
print(item_list)

['backpack', 'computer', 'ballpoint', 'sunglasses']


* `Conditional` statements can be used with a list.


* The elements of a list can be checked using an if statement and the keyword **`in`** as follows:

In [74]:
if "sugar" in item_list:
  print("sugar is present in the list")
else:
  print("sugar is not present in the list")

sugar is not present in the list


### **1.5.2 Tuples**

* A **`tuple`** is immutable and ordered collection of items.

* In Python, tuples are specified using round brackets or parentheses `()`. The following code creates a tuple:

In [75]:
py_stat = ("Python", "for", "statistics")
print(py_stat)

('Python', 'for', 'statistics')


Elements of a tuple can be accessed using `[ ]`. For instance:

In [76]:
print(py_stat[2])

statistics


* Similar to lists, we can use negative indexing and a range of indexing in `tuple`.

* Since tuples are immutable, the values present in a tuple are not changed once it is created.

* We can use loops to go through the elements of a tuple.

* The keyword in can be used to determine if a specified element is present in a tuple.

* The method **`len()`** finds out the number of items present in a tuple.

* The + operator can be employed to join two or more tuples together.


* To delete a tuple, use the statement **`delpy_stat`**.


* The tuple method **`count()`** returns the number of times a particular value appears in a tuple.

In [77]:
py_stat2 = ('Python', 'has support for',
            'statistics', 'Python')
print(py_stat2.count('stat'))
print(py_stat2.count('Python'))
len(py_stat2)

0
2


4

The tuple method **`index()`** is used to search the tuple for a
particular value. It returns the position where the specified
value is found. For example, type the following code:

In [79]:
print(py_stat2.index('statistics'))
print(py_stat2.index('Python'))
print(py_stat2.index('has support for'))

2
0
1


A ValueError is printed if the value to be indexed for does not exist in the tuple.

### **1.5.3 Sets**

* A set is an unindexed and unordered collection of items.


* Python specifies sets using curly brackets { }. For example,type the following code.

In [80]:
my_animals = {"cat", "dog", "tiger", "fox"}
print(my_animals)

{'tiger', 'dog', 'fox', 'cat'}


* No index is linked to set items because sets are unordered.


* Nevertheless, a loop can be used to go through the set elements.

* The printed output follows no order. The keyword in is used to check if a particular value is present in a set.

In [81]:
for x in my_animals:
  print(x)

tiger
dog
fox
cat


In [82]:
print("tiger" in my_animals)
print("lion" in my_animals)

True
False


Once a set is created, its elements cannot be changed. But new elements can be added.

* The method **add( )** adds a single
element to a set.

In [83]:
my_animals = {"cat", "dog", "tiger", "fox"}
my_animals.add("lion")
print(my_animals)

{'tiger', 'dog', 'cat', 'fox', 'lion'}


The output of the aforementioned program displays items without any order.

* The method **update( )** adds multiple elements to a set.

In [84]:
my_animals.update(["sheep", "goat", "sheep"])
print(my_animals)

{'tiger', 'dog', 'cat', 'goat', 'fox', 'sheep', 'lion'}


The item `'sheep'` appears once in the output because sets do not allow duplicate entries.

* To find the number of elements of a set, we use the method **len(my_animals)**.

In [85]:
len(my_animals)

7

To remove an element in a set, we use either the method **remove( )** or the method **discard( )**.

* For instance, we remove `“tiger”` as follows:

In [86]:
my_animals = {"cat", "dog", "tiger", "fox"}
my_animals.remove("tiger")
print(my_animals)

{'dog', 'fox', 'cat'}


In [87]:
my_animals.discard("cat")
print(my_animals)

{'dog', 'fox'}


* Two or more sets can be joined together using the method **`union()`**.


* Alternatively, the method **`update()`** can be used
to insert elements from one set into another.


* Let us try the following code:

In [88]:
my_set1 = {"X", "Y", "Z"}
my_set2 = {4, 5, 6}
my_set3 = my_set1.union(my_set2)
print(my_set3)

{'X', 'Y', 4, 5, 'Z', 6}


In [89]:
my_set1.update("P", "Q", "R")
my_set4 = my_set2.union(my_set1)
print(my_set4)


{4, 5, 6, 'X', 'Y', 'R', 'Z', 'Q', 'P'}


* Moreover, the method **`pop( )`** removes the last item from a set.


* The method **`clear ( )`** empties the set, and the keyword **`del`** before the name of the set deletes the set completely.

In [90]:
my_set4 = my_set1.pop()
print(my_set4)

X


### **1.5.4 Dictionaries**

* A dictionary is a mutable, unordered, and indexed collection of items.

* A dictionary in Python has a key:value pair for each of its elements.

* Dictionaries retrieve values when the keys are known. To create a dictionary, we use **`curly braces { }`**, and put key: value elements inside these braces where each pair is separated from others by commas.

* For example, the following piece of code creates a dictionary named `py_stat_dict`.

In [91]:
py_stat_dict = {
    "name": "Python",
    "purpose": "Statistics",
    "year": 2020
}
print(py_stat_dict)

{'name': 'Python', 'purpose': 'Statistics', 'year': 2020}


* The dictionaries require the keys to be unique and immutable string, number, or tuple.

* The values, on the other hand, can be of any data type and can repeat.

* Square brackets are used to refer to a key name to access a specified value of a dictionary.

In [92]:
print(py_stat_dict['name']) # accesses value for key 'name'
print(py_stat_dict.get('purpose')) # accesses value for key 'purpose'

Python
Statistics


A message: *`None`* is displayed if we try to access a non-existent key.

In [93]:
print(py_stat_dict.get('address'))

None


* We get the error: **`KeyError: 'address'`** to indicate that the key `'address'` does not exist, when we run print(py_stat_dict[`'address'`]).


In [95]:
print(py_stat_dict['address'])

KeyError: 'address'

* The value of an element can be changed by referring to its key, as shown below.

In [96]:
py_stat_dict["year"] = 2024
py_stat_dict

{'name': 'Python', 'purpose': 'Statistics', 'year': 2024}

* A **`for loop`** can be used to go through a dictionary; it returns *`keys`* of the dictionary.

In [97]:
for q in py_stat_dict:
  print(q)

name
purpose
year


The *`values`* can be returned as well.

In [98]:
for q in py_stat_dict:
  print(py_stat_dict[q])

Python
Statistics
2024


* The same output is obtained when we use the following:

In [99]:
for k in py_stat_dict.values():
  print(k)

Python
Statistics
2024


* To access both *`keys`* and *`values`* together, we use the method **`items()`** as follows.

In [100]:
for x, y in py_stat_dict.items():
  print(x, y)

name Python
purpose Statistics
year 2024


* To check if a *`key`* exists within a dictionary, we employ a conditional **`if`** statement.

In [101]:
if "purpose" in py_stat_dict:
  print("'purpose' is one of a valid keys")
else:
  print("'purpose' is not one of the valid keys")

'purpose' is one of a valid keys


We add a new element to a dictionary.

* For this, a new key is used, and a value is assigned to this key, as given below.

In [102]:
py_stat_dict["pages"] = 300
print(py_stat_dict)

{'name': 'Python', 'purpose': 'Statistics', 'year': 2024, 'pages': 300}


In [103]:
py_stat_dict["purpose"] = "Data Science"
print(py_stat_dict)

{'name': 'Python', 'purpose': 'Data Science', 'year': 2024, 'pages': 300}


* The method **`pop()`** can be used to remove a specific element.

In [104]:
py_stat_dict.pop("year") # del py_stat_dict[“year”] does the same job.
print(py_stat_dict)

{'name': 'Python', 'purpose': 'Data Science', 'pages': 300}


* The keyword **`del`** removes the whole dictionary when we use **`del py_stat_dict**. The method **`clear()`** deletes all the elements of a dictionary.

In [105]:
py_stat_dict.clear()
py_stat_dict

{}

The method **`len(dictionay_name)`** is used to print the number of **`key:value`** pairs present in the dictionary.

In [106]:
py_stat_dict = {
    "name": "Python",
    "purpose": "Statistics",
    "year": 2020
}
print(len(py_stat_dict))

3


* A dictionary cannot be copied by a simple assignment such as **`py_stat_dict2 = py_stat_dict`**.

* It is because py_stat_dict2
is just a reference to the original dictionary py_stat_dict. Whatever changes are made to py_stat_dict are automatically made to py_stat_dict2, as well.

* To copy the elements of a
dictionary, we use the method **`copy()`** as follows.

In [107]:
py_stat_dict2 = py_stat_dict.copy()
print(py_stat_dict)
print(py_stat_dict2)

{'name': 'Python', 'purpose': 'Statistics', 'year': 2020}
{'name': 'Python', 'purpose': 'Statistics', 'year': 2020}


[**`Further Reading:`** A detailed tutorial on Python is given in ](https://docs.python.org/3/tutorial/)

## **1.6 Python Libraries for Statistics**

The Anaconda distribution of Python includes suitable packages and libraries that can readily be used for statistical tasks. The following libraries will be used right through this
book:

  1. **`NumPy`** for mathematical functions,
  2. **`Pandas`** for data processing,
  3. **`Statistics:`** Python's built-in module for Statistical functions,
  4. **`Matplotlib`** for visualization and plotting,
  5. **`SciPy.stats`** module for basic and advanced statistical functions,
  6. **`Statsmodels`** for statistical models,
  7. **`PyMC`** for Bayesian modeling and inference.

All except the PyMC library are pre-installed in Anaconda distribution. We shall discuss the installation of the PyMC in subsequent Section. The details of these libraries are given in the
following sections.

### **1.6.1 NumPy for Mathematical Functions**

 **`NumPy,`** or Numerical Python, is a Python library that supports multi-dimensional arrays and matrices.


* It provides a sizable collection of fast numeric functions to work with these arrays
and to perform operations of linear algebra on them.


* In most programming languages, including Python, arrays are used to store multiple values in a variable.


* An **`array`** is a variable that is able to hold several values. Arrays are commonly used
to store statistical data.

* In standard Python, lists are used as
arrays. However, lists are slow to work with.


In case speed is an important factor, we use **`NumPy's array`** object, also called **`ndarray`**, that is significantly faster than a list.


* To create and use **`nd arrays`**, we first need to import the NumPy library. Often, we use an alias to refer to the name of different
libraries. NumPy is usually replaced with its defined alias **`np`**.


To create NumPy arrays, we type the following code.

In [108]:
import numpy as np
import torch
my_arr0 = np.array(20)
my_arr1 = np.array([10, 20, 30, 40, 50])
print(my_arr0)
print(my_arr1)
my_arr1.shape

20
[10 20 30 40 50]


(5,)

The scalar values are considered as 0-dimensional arrays.

* An array of scalar or 0-dimensional values is called a 1-dimensional array. The variable **my_arr0** in the aforementioned program
is a 0-dimensional array, whereas variable **my_arr1** is a 1-dimensional array

### **1.6.2 Special Matrices**

#### **1.6.2.1 Transposed Matrix**

A matrix in which the rows and columns of $m \times n$ --dimensional matrix $A$ are exchanged is called $A$'s transposed matrix and is represented by $A^{T}$. The dimension of a transposed matrix is $n \times m$.

In [109]:
import numpy as np
import torch

##### **1. Vector Transposition**

In [110]:
x = np.array([25, 2, 5])
print(x)

[25  2  5]


In [111]:
x.shape

(3,)

In [112]:
x = np.array([[25, 2, 5]])
print(x)

[[25  2  5]]


In [113]:
x.shape

(1, 3)

In [114]:
print(x.T)

[[25]
 [ 2]
 [ 5]]


In [115]:
print(x.T.shape) # shape tells us the dimmensions of a matrix

(3, 1)


In [116]:
x_p = torch.tensor([25, 2, 5])
print(x_p)

tensor([25,  2,  5])


In [117]:
x_p.T
x_p.shape

<ipython-input-117-9b01c19e570c>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  x_p.T


torch.Size([3])

In [118]:
x_p = torch.tensor([[25, 3, 5]])
x_p

tensor([[25,  3,  5]])

In [119]:
x_p.T

tensor([[25],
        [ 3],
        [ 5]])

In [120]:
x_p.shape

torch.Size([1, 3])

In [121]:
x_p.view(3,1)

tensor([[25],
        [ 3],
        [ 5]])

##### **2. The Norm of a Vector ($L^{2}$ Norm)**

To calculate the $L^{2}$ **`norm`** of a vector, take the square root of the sum of the squared vector values. For example, if
$$\begin{equation}
\vec{x} =
\begin{bmatrix}
x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{bmatrix}
\end{equation}$$
norm of $x$ is given by $$ |x| = \sqrt{\sum_{i=1}^k |x_i|^{2}}$$   

In [122]:
x = np.array([[25, 2, 5]])
x_norm = (25**2 + 2**2 + 5**2)**(1/2)
x_norm

25.573423705088842

In [123]:
x_norm = np.linalg.norm(x)
x_norm

25.573423705088842

##### **2. Matrix Transposition**

In [124]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [125]:
X.shape

(3, 2)

In [126]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [127]:
X.T.shape

(2, 3)

In [128]:
X_trans = np.transpose(X)
X_trans

array([[25,  5,  3],
       [ 2, 26,  7]])

Transpose of the transpose matrix becomes the original matrix. $(A^{T})^{T} = A$.

In [129]:
X = (X.T).T
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

The following relationship holds for the transpose of the matrix product between two matrices. $$(A \cdot B)^{T} = B^{T} ⋅ A^{T}$$

#### **1.6.2.2 Square Matrix**

A matrix with the same row and column dimensions is called a **`square matrix`**, and the transpose of the square matrix is exchanged for the values of the elements other than the diagonal.

In [130]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
AT = np.transpose(A)
AT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### **1.6.2.3 Identity Matrix**

The **`identity matrix`**  is a matrix in which the diagonal elements are all **1** and all other elements are **0**, and are represented by $I_{n},$, where $n$ is the number of rows or columns.

* The matrix product with the identity matrix makes that matrix itself. $$AI = A$$

The **`np.eye(n)`** function can be used to create an $n \times n$ dimension identity matrix”



In [132]:
I2 = np.eye(2)
I2


array([[1., 0.],
       [0., 1.]])

In [133]:
I3 = np.eye(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### **1.6.2.4 Trace of a Matrix**

The sum of the diagonal elements of a square matrix is called the **`trace of the matrix`** and is represented by **`tr(A)`**. It is calculated using the **`np.trace(A)`** function.

In [134]:
tr_A = np.trace(A)
tr_A

15

In [135]:
tr_A = 0
for i in range(A.shape[0]):
  tr_A = tr_A + A[i, i]
tr_A

15

#### **1.6.2.5 Diagonal Matrix**

A square matrix in which all the entries off the main diagonal are zero is called a **`diagonal matrix.`** Here are examples of some diagonal matices:
$$ A = \begin{bmatrix}
2 & \phantom{-}0\\
0 & -5
\end{bmatrix},
B = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix},
C = \begin{bmatrix}
0 & 0\\
0 & 0
\end{bmatrix}
$$

In [136]:
A = np.diag([2, -5])
A

array([[ 2,  0],
       [ 0, -5]])

In [137]:
B = np.diag([1, 1, 1])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [138]:
C = np.diag([0, 0])
C

array([[0, 0],
       [0, 0]])

#### **1.6.2.6 Triangular Matrix**

The triangular matrix can be divided into a lower triangular matrix and an upper triangular matrix based on the diagonal elements of the matrix.



##### **1. Lower Triangular**

* A **`matrix`** in which all the elements above the **principal (main)** elements are zero.

* Using **`np.tril()`**

##### **2. Upper Triangular**

* A matrix in which all the elements below the **principal (main)** elements are zero.

* Using **`np.triu()`**

We use the function of numpy random module **`randint()`** to create random matrix object.

In [139]:
M = np.random.randint(1, 10, (3, 3))
M

array([[1, 4, 6],
       [6, 2, 8],
       [3, 1, 3]])

In [140]:
M = np.random.randint(2, 10, 9).reshape((3,3))
M

array([[4, 5, 3],
       [7, 5, 5],
       [2, 8, 8]])

In [141]:
M_l = np.tril(M)
M_l

array([[4, 0, 0],
       [7, 5, 0],
       [2, 8, 8]])

In [142]:
M_u = np.triu(M)
M_u

array([[4, 5, 3],
       [0, 5, 5],
       [0, 0, 8]])

In [143]:
M_p = np.triu(M, k = 1)
M_p

array([[0, 5, 3],
       [0, 0, 5],
       [0, 0, 0]])

The triangular matrix has the following characteristics.

* The transposed matrix of the lower triangular matrix becomes the upper triangular matrix and vice versa.

In [144]:
M_l.T

array([[4, 7, 2],
       [0, 5, 8],
       [0, 0, 8]])

In [145]:
M_u.T

array([[4, 0, 0],
       [5, 5, 0],
       [3, 5, 8]])

If the diagonal elements of the triangular matrix are all 0, it becomes an **`irreversible matrix`**.

* An irreversible matrix is a matrix that does not have an **`inverse matrix`**
 , and its **`determinant`**
 is 0.



In [146]:
M_p

array([[0, 5, 3],
       [0, 0, 5],
       [0, 0, 0]])

In [147]:
import numpy as np
import torch

detM_p = np.linalg.det(M_p)
detM_p

0.0

* The inverse matrix from the upper triangle matrix and the lower triangle matrix are the upper triangle matrix and the lower triangle matrix, respectively.

#### **1.6.2.6 Symmetric Matrix**

A square matrix $A$ is said to be **`symmetric`** if $ A = A^{T}$.

The following matrices are symmetric since each is equal to its own transpose (verify):
$$ \begin{bmatrix}
\phantom{-}7 & -3\\
-3 & \phantom{-}5
\end{bmatrix}, \quad
\begin{bmatrix}
1 & 4 & 5\\
4 & 2 & 6\\
5 & 6 & 1
\end{bmatrix},\quad
\begin{bmatrix}
d_{1} & 0 & 0 & 0\\
0 & d_{2} & 0 & 0 \\
0 & 0 & d_{3} & 0 \\
0 & 0 & 0 & d_{4}
\end{bmatrix}
$$

In [148]:
A = np.array([[7, -3], [-3, 5]])
A

array([[ 7, -3],
       [-3,  5]])

In [149]:
AT = np.array(A.T)
AT

array([[ 7, -3],
       [-3,  5]])

In [150]:
print(A == AT)

[[ True  True]
 [ True  True]]


### **1.6.3 Matrix Operation**

Two $m \times n$ matrices $A$ and $B$ are **equal** if they have the same number of rows and columns and their corresponsding entries are equal.

#### **1.6.3.1 Addition and Scalar Multiplication**

If $A$ and $B$ are two $m \times n$ matrices, then the **sum** of the matrices $A + B$ is the $m \times n$ matrix with the real number $ij$ term given by $a_{ij} + b_{ij}$. The **scalar product** of the matrix A with real number $c$, denoted by $cA$, is the $m \times n$ matrix with the $ij$ term given by $ca_{ij}$.

Perform the operations on the matrices:
$$ A = \begin{bmatrix}
\phantom{-}2 & 0 & \phantom{-}1\\
\phantom{-}4 & 3 & -1\\
-3 & 6 & \phantom{-}5
\end{bmatrix}, \quad \text{and} \quad
\begin{bmatrix}
-2 & 3 & -1\\
\phantom{-}3 & 5 & \phantom{-}6\\
\phantom{-}4 & 2 & \phantom{-}1
\end{bmatrix}
$$ \\


**(a)** $A + B$  $\quad \quad $ **(b)** $2A -3B$

In [151]:
A = np.array([[2, 0, 1], [4, 3, -1], [-3, 6, 5]])
A

array([[ 2,  0,  1],
       [ 4,  3, -1],
       [-3,  6,  5]])

In [152]:
B = np.array([[-2, 3, -1], [3, 5, 6], [4, 2, 1]])
B

array([[-2,  3, -1],
       [ 3,  5,  6],
       [ 4,  2,  1]])

In [153]:
C = A + B
C

array([[0, 3, 0],
       [7, 8, 5],
       [1, 8, 6]])

In [155]:
D = 2*A - 3*B
D

array([[ 10,  -9,   5],
       [ -1,  -9, -20],
       [-18,   6,   7]])

#### **1.6.3.2 Matrix Multiplication**

We have defined matrix addition and a scalar multiplication, and we observed that these operations satisfy many of the analogous properties for real numbers. We have not yet considered the *`product`* of two matrices. Matrix multiplication is more difficult to define and is developed from the *`dot product`* of two vectors.

##### **1. Dot Product of Vectors**
Given two vectors
$$
\textbf{u} = \begin{bmatrix}
u_{1}\\
u_{2}\\
\vdots \\
u_{3}
\end{bmatrix} \quad \quad \text{and} \quad \quad
\textbf{v} = \begin{bmatrix}
v_{1}\\
v_{2}\\
\vdots \\
v_{3}
\end{bmatrix}
$$ \\
the **`dot product`** is defined by $$\textbf{u}\cdot \textbf{v} = u_{1}v_{1} + u_{2}v_{2} + \dots + u_{n}v_{n} =  \sum_{i=1}^{n} u_{1}v_{1} $$